spring.profiles.active: development,drda
# SELECT FIRST 10 sd_judge_prid judge_prid,
cmecf.selectAttorneySchedules.sql: >
    SELECT FIRST 10 sd_judge_prid judge_prid,
    cad_to_datetime(sd_dtset, sd_tmset, sd_tmset_am_pm) scheduled_on,
    cs_year case_year,
    TRIM(cs_type) case_type,
    cs_number case_number,
    cad_UndoMeta(cs_office) case_office,
    cs_def_num defendant_number,
    cad_UndoMeta(TRIM(CASE WHEN TRIM(lower(cs_type)) IN ('cr','mj','po')
      THEN (SELECT TRIM(cad_UndoMeta('USA v. ' || TRIM(NVL(py_last_name,'')) || ', ' || TRIM(NVL(py_first_name,'')) || ' ' || TRIM(NVL(py_middle_name,'')))) FROM party WHERE py_caseid = cs_caseid AND py_def_num = cs_def_num AND py_aliaseq = 0 AND py_role = 'dft')
    ELSE cs_short_title
    END)) case_title,
    cad_UndoMeta(TRIM(cs_short_name1)) caseshortname1,
    cad_UndoMeta(TRIM(cs_short_name2)) caseshortname2,
    CASE
    WHEN sd_judge_prid IS NULL
       THEN '341'
    ELSE
       (SELECT TRIM(nvl(pr_initials, '341'))
       FROM person
       WHERE pr_prid = sd_judge_prid)
    END judgeinitials,
    sd_caseid caseid,
    sd_scid,
    (   SELECT cad_UndoMeta(TRIM(co_translation)) FROM codes
       WHERE TRIM(co_code) = TRIM(sd_loc)
       AND co_type = 'location'
    ) location,
    cad_UndoMeta(TRIM(dl_description)) description,
    at_e_mail attorneyemail,
    at_atprid_ptr attorneyprid
    FROM schedule
    JOIN case ON cs_caseid = sd_caseid
    JOIN deadlines ON dl_type = sd_type AND dl_class = sd_class
    JOIN attorney ON cs_caseid = at_caseid
    WHERE NVL(sd_dtset, '') != ''
    AND cad_to_datetime(sd_dtset, sd_tmset, sd_tmset_am_pm) >= CURRENT
    AND sd_class = 'hrg'
    AND sd_dtsatis IS NULL
    AND sd_date_term IS NULL
    ORDER BY at_atprid_ptr, sd_dtset, sd_tmset_am_pm, sd_tmset

---
spring.profiles: development
informix:
    host: wiwddb.wiwd.gtwy.dcn
    port: 7102
    database: wiwd_live
    driver.classname: com.ibm.db2.jcc.DB2Driver
spring.cmecfDatasource:
    url: jdbc:ids://${informix.host}:${informix.port}/${informix.database}
    driverClassName: ${informix.driver.classname}
    username: ${informix.username}
    password: ${informix.password}
    validation-query: select 1 from systables

---
spring.profiles: drda
informix:
    port: 7102
    driver.classname: com.ibm.db2.jcc.DB2Driver
spring.cmecfDatasource:
    url: jdbc:ids://${informix.host}:${informix.port}/${informix.database}

---
spring.profiles: sqli
informix:
    server: wiwd_ecf
    port: 7101
    driver.classname: com.informix.jdbc.IfxDriver
spring.cmecfDatasource:
    url: jdbc:informix-sqli://${informix.host}:${informix.port}/${informix.database}:informixserver=${informix.server}
